services:
  postgres:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  postgres-migrations:
    build: ./backend
    command: npm run db:migrate
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules

  backend:
    build: ./backend
    ports:
      - "3333:3333"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres-migrations:
        condition: service_completed_successfully
    env_file:
      - ./backend/.env
