/** Fluid layout tokens — mobile-first; scale up via breakpoints in components. */
export const layout = {
  pageInsetX: 'clamp(16px, 4.5vw, 28px)',
  pageInsetY: 'clamp(12px, 2.5vh, 24px)',
  sectionGap: 'clamp(20px, 4vh, 32px)',
  cardInset: 'clamp(16px, 4vw, 24px)',
  safeTop: 'env(safe-area-inset-top, 0px)',
  safeBottom: 'env(safe-area-inset-bottom, 0px)',
  safeLeft: 'env(safe-area-inset-left, 0px)',
  safeRight: 'env(safe-area-inset-right, 0px)',
  touchTarget: '44px',
  authCardMax: '420px',
  authCardMaxMd: '480px',
  authCardMaxLg: '520px',
  authCardWideMax: '480px',
  authCardWideMaxMd: '540px',
  authCardWideMaxLg: '580px',
  authCardMaxXl: '560px',
  authCardWideMaxXl: '600px',
  authSplitPrimaryMin: 'min(44vw, 640px)',
  authSplitContextMin: 'minmax(0, 1fr)',
  authSplitGap: '0',
  authPrimaryPaddingXl: 'clamp(40px, 4vw, 72px)',
  authContextPadding: 'clamp(32px, 4vw, 64px)',
  authContextInnerMax: '720px',
  dashboardContentMax: '720px',
  dashboardContentWide: '840px',
  appShellMax: '1120px',
  authShellPadding: 'clamp(28px, 5vh, 56px) clamp(24px, 6vw, 96px)',
  authShellPaddingMd: 'clamp(32px, 5vh, 64px) clamp(28px, 5vw, 48px)',
  authCardPaddingMd: 'clamp(28px, 4vw, 36px)',
  authCardPaddingXl: '40px 44px 36px',
  authCardLineInset: '24px',
  authCardLineInsetLg: '28px',
  dashboardPaddingMd: 'clamp(20px, 3vh, 32px)',
  dashboardPaddingLg: 'clamp(32px, 6vw, 72px)',
  dashboardHeaderGap: 'clamp(16px, 3vh, 32px)',
  dashboardHeaderGapMd: 'clamp(20px, 3.5vh, 36px)',
  dashboardPaddingTopLg: '40px',
  atmosphereBloodRightLg: '12%',
  atmosphereCopperLeftLg: '8%',
  atmosphereBloodRightXl: '18%',
  atmosphereCopperLeftXl: '6%',
} as const
