export const spacing = {
  hairline: '1px',
  xxs: '2px',
  xxxs: '3px',
  xs: '4px',
  five: '5px',
  sm: '8px',
  six: '6px',
  nine: '9px',
  ten: '10px',
  eleven: '11px',
  md: '12px',
  thirteen: '13px',
  fourteen: '14px',
  lg: '16px',
  eighteen: '18px',
  xl: '20px',
  twentyTwo: '22px',
  xxl: '24px',
  twentyEight: '28px',
  xxxl: '32px',
  thirtySix: '36px',
  xxxxl: '40px',
  xxxxxl: '48px',
  fiftyTwo: '52px',
} as const
